Admob
NotBugGreg/UnityAdSystem pull request #6
Opened 2023-03-20 18:37 UTC by bearparadigm

Setting the right ids to the project for it to request ads in mobile. "There should be a loading screen, or a fade out that locks input when requesting an ad, until the request is over, otherwise the button repeats, delaying delivery further"

2023-03-20 19:19 UTC, NotBugGreg requested changes
please check my request

2023-03-20 19:19 UTC, NotBugGreg commented on Assets/Code/Main/AdInstaller.cs
> +                 PlayfabAdConfiguration.NAME_ONE_VIDEO_THREE_HINTS_UNIT_ID_TEST, PlayfabAdConfiguration.ONE_VIDEO_THREE_HINTS_UNIT_ID);
can you create a method with the following logic? Select test ids when the app is being running on unity or Debug build. Select production ids when it is a Release build

2023-03-20 21:47 UTC, bearparadigm commented
the request has been fulfilled, please accept my changes '3'

2023-03-20 22:33 UTC, NotBugGreg requested changes
check my comments

2023-03-20 22:33 UTC, NotBugGreg commented on Assets/Code/Basic Implementation/PlayfabAdConfiguration.cs
> +        public static readonly string REWARD_ID = "EDITOR_SOLITAIRE_HINT_REWARD"; //for playfab
the values correct for test are -> 

- ONE_VIDEO_THREE_HINTS_UNIT_ID_TEST = "ca-app-pub-3940256099942544/5224354917"
- NAME_ONE_VIDEO_THREE_HINTS_UNIT_ID_TEST = "ONE_VIDEO_THREE_HINTS_UNIT_ID_TEST"

2023-03-20 22:33 UTC, NotBugGreg commented on Assets/Code/Basic Implementation/PlayfabAdConfiguration.cs
> +        public static readonly string REWARD_ID = "EDITOR_SOLITAIRE_HINT_REWARD"; //for playfab
and when I mentioned debug build I referred to this -> https://docs.unity3d.com/ScriptReference/Debug-isDebugBuild.html

Look for something similar for the release build

2023-03-21 14:37 UTC, NotBugGreg approved these changes

2023-03-21 20:41 UTC, merged